### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by k3rinho** [Teaching-projects/SZE-FONYA-2021-TM-Simulator#1]
Basic Simulation v1

**Comment by hegyhati** [comment]
Nem szereti az npm-em a dolgot (valoszinuleg tul regi). Dobj ossze egy docker image-et kerlek hozza, vagy ha nincs backend kommunikacio, akkor siman deploy-old gh-pages-re, es ugy a legegyszerubb kiprobalnom.

**Comment by k3rinho** [comment]
Ha minden igaz, akkor látható:
https://k3rinho.github.io/turing/

**Comment by hegyhati** [comment]
Szuper, koszi. Sikerult kiakasztani, a vegtelen sok blank nincs lekezelve. 
![image](https://user-images.githubusercontent.com/13832329/119399250-f4be4480-bcd8-11eb-82de-2c08a550b1bb.png)
Illetve ez nem teljesen az a definicio amit mi vettunk, mert egyszerre ir, meg lep, de annyi baj legyen. 
irom be az otost.

**Comment by hegyhati** [comment]
Jah, meg annyit pls tegyel meg, hogy itt is felpusholod egy gh-pages branchre, aztan akkro beallitom hogy ebben a repoban is elerheto legyen. (van erre gh actions action, ami amugy ezt kb megcsinalja automatikusan.)
